version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./src/config/.env.development # todo: change to .env.production
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./src/config/.env.development # todo: change to .env.production

volumes:
  db_data: {}
